### ISSUE TITLE
rbg-hex.py

### ISSUE THREAD

**Issue by rohbot25** [kamilajab/something#9]
1.run the program
2. test case doesnt work

FF7F00 shouldve printed

that was not printed
<img width="126" alt="Screen Shot 2023-03-20 at 5 48 15 PM" src="https://user-images.githubusercontent.com/104528255/226473115-5708a744-aea9-47ba-af61-34823be0cb8f.png">

macOS
intel chip

change the 1000000 to 0

yes related issue with b

high priority issue
always reproduced
high impact

**Comment by kamilajab** [comment]
thank you very helpful
